name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write # Required for GitHub Pages deployment

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      # ⬇️ Attempt to restore previous history
      - name: Download previous Allure history (if any)
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: allure-history
          path: allure-results/history

      # ✅ Generate Allure report and carry over history
      - name: Generate Allure Report
        run: |
          mkdir -p allure-report/history
          cp -r allure-results/history/* allure-report/history/ || true
          npx allure-commandline generate allure-results --clean -o allure-report

      # 🧪 Debug: confirm history exists before uploading
      - name: List Allure report history folder
        run: ls -lR allure-report/history || echo "No history found"

      # ⬆️ Upload Allure HTML report as artifact (downloadable)
      - name: Upload Allure HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # ⬆️ Upload Playwright built-in HTML report
      - name: Upload Playwright HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      # 🌐 Deploy to GitHub Pages (live Allure report)
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          keep_files: true

      # 💾 Upload history for trending (used next run)
      - name: Upload Allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-report/history
