name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Install Allure CLI
      - name: Install Allure commandline
        run: npm install -D allure-commandline

      # Restore Allure history from GitHub Actions cache
      - name: Restore Allure history cache
        uses: actions/cache@v4
        with:
          path: allure-history-cache
          key: allure-history-${{ github.ref }}

      # Copy restored history if available
      - name: Copy history from cache (if exists)
        run: |
          mkdir -p allure-results/history
          cp -r allure-history-cache/* allure-results/history/ || echo "No cached history to copy"

      # Run Playwright tests and generate allure results
      - name: Run Playwright tests
        run: npx playwright test

      # Prepare output folder for report
      - name: Prepare Allure report folder
        run: mkdir -p allure-report/history

      # Generate Allure HTML report
      - name: Generate Allure Report
        run: npx allure-commandline generate allure-results --clean -o allure-report

      # Save history to cache folder for next run
      - name: Save updated Allure history to cache folder
        run: |
          mkdir -p allure-history-cache
          cp -r allure-report/history/* allure-history-cache/ || echo "No history to save"

      # Upload Allure history artifact
      - name: Upload Allure history artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-history
          path: allure-report/history

      # Upload Allure HTML report
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # Upload Playwright HTML report
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      # Deploy Allure report to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
