name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # 👇 Essential step to fix your issue
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Install Allure CLI
        run: npm install -D allure-commandline

      - name: Run Playwright tests
        run: npx playwright test
        continue-on-error: true

      # Generate Allure HTML report
      - name: Generate Allure Report
        run: |
          if [ -d allure-results ]; then
            npx allure-commandline generate allure-results --clean -o allure-report
          else
            echo "No allure-results directory found!"
            exit 1
          fi

      # Upload Allure Report Artifact
      - name: Upload Allure report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      # Upload Playwright HTML report
      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

      # Deploy Allure report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        if: github.ref == 'refs/heads/main' && success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
